[package]
name = "sdkwork-api-modelkit-standalone-gateway"
version.workspace = true
edition.workspace = true

[[bin]]
name = "sdkwork-api-modelkit-standalone-gateway"
path = "src/main.rs"

[dependencies]
axum.workspace = true
sdkwork-api-modelkit-assembly.workspace = true
sdkwork-web-bootstrap.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
